name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, m87]
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }}) for ${{ matrix.cp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
        arch: [auto64, arm64]
        cp: ["cp3{11,12}"]
        include:
          - os: macos-14
            arch: arm64
            cp: "cp3{11,12}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache/restore@v4
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
        with:
          path: |
            gn
            skia
          key: linux-aarch64-skia-${{ github.sha }}

      - name: Set up QEMU
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "${{ matrix.cp }}-*"
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT_MACOS: TARGET_ARCH=${{ matrix.arch }}
          CIBW_ENVIRONMENT_LINUX: CI_SKIP_BUILD=true
          CIBW_BEFORE_ALL: bash scripts/build_${{ runner.os }}.sh
          CIBW_BEFORE_BUILD: pip install pybind11 numpy
          CIBW_TEST_REQUIRES: pytest pillow glfw
          CIBW_TEST_REQUIRES_MACOS: pytest pillow pyopengl glfw
          CIBW_TEST_COMMAND: python -m pytest {project}/tests
          CIBW_TEST_COMMAND_LINUX: >
            xvfb-run -s "-screen 0 640x480x24" python -m pytest {project}/tests
        ## wheel testing on macos-11/arm64 in github CI is disabled with a warning:
        ## "while arm64 wheels can be built on x86_64, they cannot be tested. ..."
        ## with a suggestion of adding the following line:
        #  CIBW_TEST_SKIP: "*-macosx_arm64"
        ## This is no longer the case for 'macos-14' (arm64 by default). 'macos-13'
        ## is still x86_64.
        ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        ## 'macos-11' will no longer be available after 6/28/2024

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.cp }}
          path: ./wheelhouse/*.whl

  build_docs:
    name: Build docs
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.8'

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Build docs
        run: |
          python -m pip install -f dist skia-python
          python -m pip install sphinx==6.2.1 sphinx-rtd-theme
          python setup.py build_sphinx

      - name: Deploy docs
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

  publish:
    name: Upload packages to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/skia-python/
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
